@startuml
actor User
participant "Express Router" as Router
participant Stripe
database MongoDB

User -> Router: POST /products
activate Router
Router -> Stripe: stripe.products.create()
activate Stripe
Stripe -> MongoDB: Product.create()
activate MongoDB
MongoDB --> Stripe: Success
deactivate MongoDB
Stripe --> Router: Success
deactivate Stripe
Router --> User: Success
deactivate Router

User -> Router: POST /products/:id
activate Router
Router -> Stripe: stripe.products.update()
activate Stripe
Stripe --> Router: product
deactivate Stripe
Router --> MongoDB: Product.findOneAndUpdate()
activate MongoDB
MongoDB --> Router: newdata
deactivate MongoDB
Router --> User: Success
deactivate Router

User -> Router: GET /products/:id
activate Router
Router -> Stripe: stripe.products.retrieve()
activate Stripe
Stripe --> Router: product
deactivate Stripe
Router --> User: product
deactivate Router

User -> Router: GET /products
activate Router
Router -> Stripe: stripe.products.list()
activate Stripe
Stripe --> Router: products
deactivate Stripe
Router --> User: products
deactivate Router

User -> Router: DELETE /products/:id
activate Router
Router -> Stripe: stripe.products.delete()
activate Stripe
Stripe --> Router: deleted
deactivate Stripe
Router --> MongoDB: Product.deleteOne()
activate MongoDB
MongoDB --> Router: deleted
Router --> User: Success
deactivate Router

@enduml